### ISSUE TITLE
Is it possible to include this module without extending the Math object?

### ISSUE THREAD

**Issue by pillowfication** [davidbau/seedrandom#61] opened 2019-02-23 00:50 UTC
I don't want this package to extend or modify any native objects when I use it.

```javascript
const seedrandom = require('seedrandom')
typeof Math.seedrandom // should be 'undefined'
```

**Comment by davidbau** [comment] 2019-02-23 11:47
Good point.   Duplicate of #20.  Continue the discussion there.

**Closed by davidbau** 2019-02-23 11:47 UTC
