### ISSUE TITLE
TypeError: Object #<Object> has no method 'seedrandom'

### ISSUE THREAD

**Issue by yoav-zibin** [davidbau/seedrandom#22] opened 2015-03-08 17:45 UTC
(Thanks again for an awesome project!)

My usage is really simple:
  <script src="http://cdnjs.cloudflare.com/ajax/libs/seedrandom/2.3.11/seedrandom.min.js"></script>
Then I do:
 Math.seedrandom(...)

It works really well, but I got an email with a JS error:
TypeError: Object #<Object> has no method 'seedrandom'
(I automatically send myself errors if they happened in production.)

The file seedrandom.min.js was definitely loaded because I use HTML5 manifest, so either everything loads or nothing loads :)

I really have no idea how to reproduce it, but I wanted to record the issue in case someone else runs into it in the future.

It happened for this settings:
URL: http://yoav-zibin.github.io/multiplayer-games/index.html#/main
Navigator:
        appName=Netscape,
        appCodeName=Mozilla,
        platform=Linux armv7l,
        appVersion=5.0 (Linux; Android 4.4.2; Endeavour_101L Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36,
        product=Gecko,
        userAgent=Mozilla/5.0 (Linux; Android 4.4.2; Endeavour_101L Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36,
        vendor=Google Inc.

**Comment by davidbau** [comment] 2015-03-08 18:48
The page http://yoav-zibin.github.io/multiplayer-games/index.html doesn't
exist for me.

**Comment by yoav-zibin** [comment] 2015-03-08 19:02
Really???
I've tried it in FF, Chrome and Safari just now and it works fine for me.
Can you open the console and email me (yoav.zibin@gmail.com) any errors you
see? I would really appreciate it :)
(It's intended to be loaded from inside a mobile browser:
https://play.google.com/store/apps/details?id=com.yoavzibin.megagame )

**Comment by davidbau** [comment] 2015-03-08 19:13
Ah, it's my home firewall (for the kids) that's picking up on
"multiplayer-games" in the URL.  I'll look again.

**Comment by davidbau** [comment] 2015-03-08 19:20
OK, the page works for me, and like you, I cannot reproduce the problem. By
the way, I've always had problems with app manifests in my own work (though
not this sort of problem); and I'm not sure about support for app manifests
for older browsers.  Does your logging report a user agent?

David

**Comment by yoav-zibin** [comment] 2015-03-08 19:25
Yes, I added it in my bug report:
userAgent=Mozilla/5.0 (Linux; Android 4.4.2; Endeavour_101L Build/KVT49L)
> AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0
> Safari/537.36,

I can't reproduce it either. You can close this bug as non-reproducible.
If I get it more times, I'll reopen :)

**Comment by davidbau** [comment] 2015-03-08 19:45
OK.  http://caniuse.com/#feat=offline-apps only lists offline support on Chrome/40 Android, so it might not be using app manifests.  Closing as no-repro.

**Closed by davidbau** 2015-03-08 19:45 UTC
